/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation */

#ifndef _Included_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
#define _Included_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
 * Method:    comapareEqualIntInt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation_compareEqualIntInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation
 * Method:    comapareGreaterThanIntInt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_wso2_siddhi_extension_he_api_HomomorphicEncryptionEvaluation_compareGreaterThanIntInt
  (JNIEnv *, jobject, jint, jint);

void init();
void destroy();
int * convertToArray(int, int);

#ifdef __cplusplus
}
#endif
#endif
